---

- name: curl | Install curl | apt
  become: yes
  become_user: root
  apt:
    name: curl
    state: present

- name: htop | Install htop | apt
  become: yes
  become_user: root
  apt:
    name: htop
    state: present
