---

- name: curl | Install curl | apt
  become: yes
  become_user: root
  apt:
    name: curl
    state: present

- name: htop | Install htop | apt
  become: yes
  become_user: root
  apt:
    name: htop
    state: present

- name: g++ | Install g++ | apt
  become: yes
  become_user: root
  apt:
    name: g++
    state: present

- name: cmake | Installs cmake | apt
  become: yes
  become_user: root
  apt:
    name: cmake
    state: present

- name: pip | Install pip | apt
  become: yes
  become_user: root
  apt:
    name: pip
    state: present

- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: npm | Install npm
  shell: nvm use 16

- name: rust/cargo | Install rust/cargo | curl
  block:
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust
  become: yes
  become_user: "{{ qfiles.username }}"
