ZSH=$HOME/.oh-my-zsh

# You can change the theme with another one:
#   https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"
plugins=(fzf git vi-mode gcloud kubectl kube-ps1 gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search z docker docker-compose asdf doctl helm terraform)


# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"

unalias rm # No interactive rm by default (brought by plugins/common-aliases)

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
export BUNDLER_EDITOR="nvim"
export EDITOR="nvim"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Make CTRL-Z background things and unbackground them.
function fg-bg() {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    zle push-input
  fi
}
zle -N fg-bg
bindkey '^Z' fg-bg
